export const PUBLIC_ENV = {
    APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT,
    GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
    GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
};
